// <auto-generated />
namespace DropDownTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Firstemployeeschema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Firstemployeeschema));
        
        string IMigrationMetadata.Id
        {
            get { return "201705310923374_First employee schema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
